apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: <PORT>
