apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      nodePort: <PORT>
  selector:
    app: app
