apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 5000
      name: http
      nodePort: <PORT>
  selector:
    app: api
